---
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

$$\text{EC 570} \\
\text{Fall 2021} \\
\text{Homework Assignment #6} \\
\text{Due date: November 25 2021}$$

$\text{Brannigan Vogt}$

**Question 1 (10 points)**

We know that in linear probability models (LPM) we should always use heteroskedasticity-robust standard errors. However, in LPMs we also know the functional form of the heteroskedasticity that we can use to obtain more efficient estimators. Suppose that the dependent variable $y$ is a binary variable and $x$ be the $1 \times K$ vector of explanatory variables. Suppose that we have the following LPM model

$$E[y | x] = Prob( y = 1 | x) = x\beta ≡ p(x)$$

  1. Write the conditional variance function $Var(y│x)$. **[2 points]**

***

$$Y = X\beta + U \\
\implies Var(Y│X) = Var(U│X) \\
Var(y│x) = E[y | x]* (1 - E[y|x]) \\
Var(y│x) = x\beta * (1 - x\beta)\\
Var(y│x) = x\beta - (x\beta)^2$$

\newpage

  2. What will you use as weights $(h_i)$ in the WLS estimation procedure given your answers above? **[2 points]**

***

We're assuming random sampling. Use $\frac{1}{\sqrt{h_i}}$ means each square residual weighted by $\frac{1}{h_i}$.

Given my answer above, in order to get a constant variance (account for heteroskedasticity) we will use the following as weights in the WLS estimation procedure.

$$h_i = h(x_i) = x\beta [1 - x\beta]\\
\implies \frac{1}{\sqrt{h_i}} = \frac{1}{\sqrt{ x\beta [1 - x\beta]}}$$

\newpage

  3. Carefully explain the steps (in detail) how will you obtain the Feasible GLS estimators for the coefficients $\beta$ based on the functional form the heteroskedasticity in LPMs. **[4 points]**

***

$$\text{ANSWER 3}$$

\newpage

  4. Given the fact that we are estimating FGLS estimator in a LPM, what is the primary issue that you would encounter obtaining the FGLS estimators using the procedure you describe above. **[2 points]**

***

In LPM, the outcome variable can only take one of two values (0 and 1) and there is always heteroskedasticity.

The weights are estimated and the functional form of thee weights was assumed. (i.e., function form of variance, functional form of heteroskedasticty)

Assuming $E[u | x] = E[u] = 0$ and proper specification of h_i, then estimation FGLS unbiased.u

$$\text{ANSWER 4}$$

\newpage

**Question 2 [18 points total]**

You are trying to measure the historical black-white gap in infant mortality using county-level data on infant mortality rates (*IMR*, the number of deaths of those aged 1 or less per 1,000 live births), the proportion of the population that is black (*pctblack*), average *income* levels (in thousands of dollars), and average years of *education.*  You have data from all US counties in 1920.  

$IMR= \beta_0 + \beta_1 pctblack + \beta_2 income + \beta_3 education + u$

Here, $\beta_1$ is your measure of the black-white gap in infant mortality and you expect that $\beta_1 > 0$, i.e. that the infant mortality rate is higher in counties with a larger black population (all else equal).

  1. You are worried that *IMR* is reported with error.  In particular, some have suggested that IMR might actually be overreported for blacks.  Researchers suggest that though deaths were accurately reported (perhaps because families were required to obtain a death certificate for a ceremonial burial), births were severely underreported for blacks.  Therefore the ratio deaths to births is possibly inflated for blacks.  In light of this, do you think the estimate $\hat{\beta_1}$ will be biased?  If there is bias, is it positive or negative?  Explain. [4 points]


***

$$\text{ANSWER 2.1}$$

\newpage

  2. You are also worried that you are leaving out an important variable: health care access.  Your reasoning is that counties without adequate access to health care will have higher *IMR* and in general, health care access is lower in counties with a larger black population (higher *pctblack*).  If this is the case, would $\hat{beta_1}$ be an over- or underestimate of $\beta_1$?  Explain. [3 points]

***


$$\text{ANSWER 2.2}$$

\newpage

  3. To deal with omitted variable bias, you also collect data on the number of physicians per capita in each county. Is this a good proxy variable for health care access based on the three assumptions we discussed in class?  (Discuss each assumption in turn. If you feel that an assumption is likely to fail then give at least one example of the case when an assumption is likely to fail. You must discuss these assumptions in terms of the variables used in the regression analysis, not in terms of $x$,$y$,$x^*$ *etc*..) **[5 points]**

***

$$\text{ANSWER 2.3}$$

\newpage

  4. Now assume that the number of physicians per capita **IS** a good proxy for health care access. How would you use this proxy variable?  How does this help you deal with the omitted variable bias discussed in part (b)? **[3 points]**


***

$$\text{ANSWER 2.4}$$

\newpage

  5. Now let’s say that you do not have data on all US counties but instead have data only on counties that chose to collect *IMR* and race data from residence (roughly about 80% of counties in 1920).  From your background research, it seems that counties with high proportions of black residents are less likely to collect *IMR* data. Should you be worried about bias and inconsistency due to sample selection? Explain. **[3 points]**

***

Seeing as proportion of the population that is black (*pctblack*) is the key explanatory variable of study here, we should definitely be worried about this sample selection problem where missing data is correlated with *pctblack* i.e., chance of being included in our sample depends on key explanatory variable in study here.

$$\text{ANSWER 2.5}$$